# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 20:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('Id_Classe', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('LibelleClasse', models.CharField(blank=True, max_length=35)),
                ('Effectif', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumSemaine', models.IntegerField(default=1)),
                ('Jour', models.CharField(max_length=15)),
                ('TypeCours', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('codeDept', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('libelleDept', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEnseignant', models.CharField(max_length=25)),
                ('prenomEnseignant', models.CharField(max_length=25)),
                ('codeDept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Departement')),
                ('codeEnseignant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('CodeFiliere', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('libelleFiliere', models.CharField(max_length=200)),
                ('PeriodeAccreditation', models.CharField(blank=True, max_length=9)),
                ('codeDept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Departement')),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('NumCreneauHoraire', models.IntegerField(primary_key=True, serialize=False)),
                ('Duree', models.IntegerField(default=1)),
                ('HeureDebut', models.TimeField(auto_now_add=True)),
                ('HeureFin', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('codeMatiere', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('LibelleMatiere', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('CodeModule', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('LibelleModule', models.CharField(max_length=200)),
                ('semestre', models.CharField(max_length=2)),
                ('CodeFiliere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('codeReservation', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('Id_Salle', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TypeSalle', models.CharField(max_length=15)),
                ('Batiment', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='Id_Salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Salle'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='NumCreneauHoraire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Horaire'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='NumSemaine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Cours'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='codeEnseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Enseignant'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='CodeModule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Module'),
        ),
        migrations.AddField(
            model_name='cours',
            name='CodeEnseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Enseignant'),
        ),
        migrations.AddField(
            model_name='cours',
            name='CodeMatiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Matiere'),
        ),
        migrations.AddField(
            model_name='cours',
            name='Id_Classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Classe'),
        ),
        migrations.AddField(
            model_name='cours',
            name='Id_Creneau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Horaire'),
        ),
        migrations.AddField(
            model_name='cours',
            name='Id_Salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Salle'),
        ),
        migrations.AddField(
            model_name='classe',
            name='CodeFiliere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Filiere'),
        ),
    ]
