# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-24 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_salle_capacite'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='Coefficient',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='matiere',
            name='VH_Cours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matiere',
            name='VH_EC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matiere',
            name='VH_TD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matiere',
            name='VH_TP',
            field=models.IntegerField(default=0),
        ),
    ]
