# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-24 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20180324_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaire',
            name='Duree',
            field=models.FloatField(default=1),
        ),
    ]
