# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-24 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20180324_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='salle',
            name='TypeSalle',
            field=models.CharField(choices=[('td', 'TD'), ('tp', 'TP'), ('cm', 'CM')], max_length=15),
        ),
    ]
