# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-24 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20180324_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horaire',
            options={'ordering': ('NumCreneauHoraire',)},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='codeReservation',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
