# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-25 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20180324_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='Jour',
            field=models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeud', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=15),
        ),
        migrations.AlterField(
            model_name='cours',
            name='TypeCours',
            field=models.CharField(choices=[('td', 'TD'), ('tp', 'TP'), ('cm', 'CM')], max_length=15),
        ),
    ]
