# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 14:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20180325_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='codeEnseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
